ALTER TABLE ANGAJAT DROP CONSTRAINT FK_ANGAJAT_DEPOZIT_IDDEPOZIT
ALTER TABLE PRODUSE DROP CONSTRAINT FK_PRODUSE_DEPOZIT_IDDEPOZIT
ALTER TABLE PRODUSE DROP CONSTRAINT FK_PRODUSE_BIBLIOTECA_IDBIBLIOTECA
ALTER TABLE CLIENT DROP CONSTRAINT FK_CLIENT_BIBLIOTECA_IDBIBLIOTECA
DROP TABLE ANGAJAT CASCADE
DROP TABLE BIBLIOTECA CASCADE
DROP TABLE PRODUSE CASCADE
DROP TABLE CLIENT CASCADE
DROP TABLE DEPOZIT CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
